### ISSUE TITLE
Ignore NSCFConstantStrings

### ISSUE THREAD

**Issue by jdewind** [mikeash/MAZeroingWeakRef#4]
Mike,

Is there any risk of simply ignoring NSCFConstantStrings since they cannot be deallocated? it would be a matter of not doing this assert if the object is an NSCFConstantString

<code>        NSCAssert(0, @"Cannot create zeroing weak reference to object of type %@ with COREFOUNDATION_HACK_LEVEL set to %d", class, COREFOUNDATION_HACK_LEVEL);</code>

**Comment by mikeash** [comment]
I'd say the only risk is that you may have some sort of design flaw if you're making ZWRs to constant strings. But perhaps there's a good reason to allow it. In any case, aside from not flagging a potentially weird situation, I see no problem.

**Comment by jdewind** [comment]
I was suggesting that you would neither ZWR a constant string or throw an exception but rather ignore it all together. For example, you might want a MAZeroingWeakDictionary that contains a weak reference to a target object and a key value path. You want a weak reference to the target object and you are indifferent to the key path (which is more than likely a constant string).

**Comment by mikeash** [comment]
Interesting point. Yes, I can see where there might be situations where you want ZWRs to objects that can have them, and it's sensible to also throw constant strings into the mix, now that you mention that. Do you want to change the code to do this, then?

**Comment by jdewind** [comment]
Indeed, I will do so.
